/* DATA DEFINITION LANGUAGE */

CREATE DATABASE Exemplo
USE Exemplo

CREATE TABLE Employees
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	Salario MONEY NOT NULL,
)

DROP TABLE Employees